<?php

// Prevent direct access to the plugin
defined( 'ABSPATH' ) || exit;

/**
 * Plugin helper functions.
 * Used by settings UI, validation, modules, and anywhere else helpers are needed.
 */

// ---------------------------------------------------------------------------
// Translation helpers (used by settings UI, validation, Translations module).
// ---------------------------------------------------------------------------

/**
 * Returns the list of translation domains for plugins and themes (single source of truth for other code).
 * Used by the Translations module settings UI and validation.
 *
 * @return array{plugins: string[], themes: string[]} Keys 'plugins' and 'themes', each an array of text domain strings.
 */
function cps_hc_gems_get_translation_domains() {
	return [
		'plugins' => [
			'acf',
			'acfml',
			'addify-eobc',
			'addify-product-qty',
			'addify_css',
			'addify_eobc',
			'addify_promo_bar',
			'addify_reg',
			'addify_rfq',
			'addify_videos',
			'admin-menu-editor-pro',
			'advanced-uptime-monitor-extension',
			'affiliate-wp',
			'affiliate-wp-lifetime-commissions',
			'affiliate-wp-recurring-referrals',
			'affiliate-wp-tiered',
			'affiliatewp-affiliate-area-shortcodes',
			'affiliatewp-affiliate-portal',
			'affiliatewp-allowed-products',
			'affiliatewp-custom-affiliate-slugs',
			'affiliatewp-direct-link-tracking',
			'affiliatewp-multi-currency',
			'affiliatewp-multi-tier-commissions',
			'affiliatewp-rest-api-extended',
			'affiliatewp-show-affiliate-coupons',
			'affiliatewp-signup-referrals',
			'affiliatewp-store-credit',
			'affiliatewp-woocommerce-redirect-affiliates',
			'affwp-affiliate-dashboard-sharing',
			'affwp-paypal-payouts',
			'all-in-one-wp-migration',
			'all-in-one-wp-migration-dropbox-extension',
			'all-in-one-wp-migration-ftp-extension',
			'all-in-one-wp-migration-gdrive-extension',
			'all-in-one-wp-migration-multisite-extension',
			'all-in-one-wp-migration-onedrive-extension',
			'all-in-one-wp-migration-unlimited-extension',
			'all-in-one-wp-migration-url-extension',
			'automatewoo',
			'automatewoo-birthdays',
			'automatewoo-referrals',
			'automatorwp',
			'automatorwp-pro',
			'bloom',
			'boilerplate-extension',
			'bought-together-for-woocommerce',
			'bricksextras',
			'bricksforge',
			'buy-again-for-woocommerce',
			'cartflows',
			'cartflows-pro',
			'checkout-wc',
			'complianz-gdpr',
			'contact-form-7-multilingual',
			'customize-my-account-page-for-woocommerce',
			'database-cleaner',
			'divi-menu-cart',
			'divi-responsive-helper',
			'divi-toolbox',
			'divipasswords',
			'dsm-supreme-modules-pro-for-divi',
			'dynamic-content-for-elementor',
			'elementor',
			'elementor-pro',
			'fluent-affiliate',
			'fluent-affiliate-pro',
			'fluent-boards',
			'fluent-boards-pro',
			'fluent-booking',
			'fluent-booking-pro',
			'fluent-cart',
			'fluent-cart-pro',
			'fluent-community',
			'fluent-community-pro',
			'fluent-crm',
			'fluent-smtp',
			'fluent-support',
			'fluent-support-pro',
			'fluentcampaign-pro',
			'fluentform',
			'fluentform-pdf',
			'fluentform-signature',
			'fluentformpro',
			'free-gifts-for-woocommerce',
			'gappointments',
			'generateblocks',
			'generateblocks-pro',
			'gp-premium',
			'gravityforms-multilingual',
			'gravitysmtp',
			'imagify',
			'it-l10n-ithemes-security-pro',
			'jet-appointments-booking',
			'jet-blocks',
			'jet-blog',
			'jet-booking',
			'jet-cw',
			'jet-elements',
			'jet-engine',
			'jet-engine-attachment-link-callback',
			'jet-engine-dynamic-charts-module',
			'jet-engine-dynamic-tables-module',
			'jet-engine-layout-switcher',
			'jet-engine-post-expiration-period',
			'jet-engine-trim-callback',
			'jet-form-builder',
			'jet-form-builder-address-autocomplete',
			'jet-form-builder-colorpicker',
			'jet-form-builder-convertkit-action',
			'jet-form-builder-formless-actions-endpoints',
			'jet-form-builder-hr-select',
			'jet-form-builder-hubspot-action',
			'jet-form-builder-limit-form-responses',
			'jet-form-builder-mailerlite-action',
			'jet-form-builder-mailpoet-action',
			'jet-form-builder-moosend-action',
			'jet-form-builder-paypal-subscriptions',
			'jet-form-builder-pdf',
			'jet-form-builder-save-progress',
			'jet-form-builder-schedule-forms',
			'jet-form-builder-select-autocomplete',
			'jet-form-builder-stripe-gateway',
			'jet-form-builder-user-login-action',
			'jet-form-builder-woo-action',
			'jet-menu',
			'jet-popup',
			'jet-reviews',
			'jet-search',
			'jet-smart-filters',
			'jet-styles-manager',
			'jet-tabs',
			'jet-theme-core',
			'jet-tricks',
			'jet-wc-product-table',
			'jet-woo-builder',
			'jet-woo-product-gallery',
			'js_composer',
			'ld-multilingual',
			'learndash',
			'learndash-2checkout',
			'learndash-achievements',
			'learndash-bbpress',
			'learndash-certificate-builder',
			'learndash-course-grid',
			'learndash-course-reviews',
			'learndash-edd',
			'learndash-elementor',
			'learndash-event-espresso',
			'learndash-gravity-forms',
			'learndash-integrity',
			'learndash-memberpress',
			'learndash-migration',
			'learndash-notifications',
			'learndash-paidmemberships',
			'learndash-restrict-content-pro',
			'learndash-samcart',
			'learndash-tec',
			'learndash-thrivecart',
			'learndash-woocommerce',
			'learndash-zapier',
			'mainwp',
			'mainwp-api-backups-extension',
			'mainwp-article-uploader-extension',
			'mainwp-atarim-extension',
			'mainwp-branding-extension',
			'mainwp-buddy-extension',
			'mainwp-bulk-settings-manager',
			'mainwp-cache-control-extension',
			'mainwp-clean-and-lock-extension',
			'mainwp-clone-extension',
			'mainwp-code-snippets-extension',
			'mainwp-comments-extension',
			'mainwp-custom-dashboard-extension',
			'mainwp-custom-post-types',
			'mainwp-database-updater-extension',
			'mainwp-domain-monitor-extension',
			'mainwp-favorites-extension',
			'mainwp-file-uploader-extension',
			'mainwp-google-analytics-extension',
			'mainwp-ithemes-security-extension',
			'mainwp-jetpack-protect-extension',
			'mainwp-jetpack-scan-extension',
			'mainwp-lighthouse-extension',
			'mainwp-maintenance-extension',
			'mainwp-piwik-extension',
			'mainwp-post-dripper-extension',
			'mainwp-post-plus-extension',
			'mainwp-pressable-extension',
			'mainwp-pro-reports-extension',
			'mainwp-rocket-extension',
			'mainwp-ssl-monitor-extension',
			'mainwp-staging-extension',
			'mainwp-sucuri-extension',
			'mainwp-team-control',
			'mainwp-timecapsule-extension',
			'mainwp-updraftplus-extension',
			'mainwp-url-extractor-extension',
			'mainwp-virusdie-extension',
			'mainwp-vulnerability-checker-extension',
			'mainwp-woocommerce-shortcuts-extension',
			'mainwp-woocommerce-status-extension',
			'mainwp-wordfence-extension',
			'mainwp-wp-compress-extension',
			'mb-admin-columns',
			'mb-blocks',
			'mb-custom-table',
			'mb-favorite-posts',
			'mb-frontend-submission',
			'mb-revision',
			'mb-settings-page',
			'mb-term-meta',
			'mb-testimonials',
			'mb-user-avatar',
			'mb-user-profile',
			'meta-box',
			'meta-box-builder',
			'meta-box-columns',
			'meta-box-conditional-logic',
			'meta-box-geolocation',
			'meta-box-group',
			'meta-box-include-exclude',
			'meta-box-show-hide',
			'meta-box-tabs',
			'meta-box-template',
			'meta-box-tooltip',
			'monarch',
			'ninja-forms-active-campaign',
			'ninja-forms-conditionals',
			'ninja-forms-excel-export',
			'ninja-forms-layout-styles',
			'ninja-forms-multi-part',
			'ninja-forms-save-progress',
			'ninja-forms-stripe',
			'ninja-forms-uploads',
			'ninja-forms-user-management',
			'ninja-forms-webhooks',
			'oxyextras',
			'oxygen',
			'oxygen-gutenberg',
			'oxygen-woocommerce',
			'perfmatters',
			'pewc',
			'plgfyplv',
			'polylang-pro',
			'polylang-wc',
			'qala-product-price-history',
			'quadmenu',
			'quadmenu-pro',
			'rcp',
			'revslider',
			'rocket',
			'sfwd-lms',
			'sitepress-multilingual-cms',
			'termageddon-for-mainwp',
			'translatepress-multilingual',
			'tutor-pro',
			'uael',
			'updraftplus',
			'userpro',
			'wc_gf_addons',
			'wc_name_your_price',
			'wc_wishlist',
			'woo-af-drpc',
			'woo-price-per-unit-pro',
			'woocommerce-account-funds',
			'woocommerce-additional-variation-images',
			'woocommerce-advanced-notifications',
			'woocommerce-all-products-for-subscriptions',
			'woocommerce-api-manager',
			'woocommerce-appointments',
			'woocommerce-back-in-stock-notifications',
			'woocommerce-bookings',
			'woocommerce-bulk-stock-management',
			'woocommerce-checkout-add-ons',
			'woocommerce-checkout-field-editor',
			'woocommerce-composite-products',
			'woocommerce-conditional-shipping-and-payments',
			'woocommerce-cost-of-goods',
			'woocommerce-deposits',
			'woocommerce-dynamic-pricing',
			'woocommerce-email-customizer',
			'woocommerce-eu-vat-number',
			'woocommerce-google-adwords-conversion-tracking-tag',
			'woocommerce-google-analytics-pro',
			'woocommerce-mailchimp-integration',
			'woocommerce-measurement-price-calculator',
			'woocommerce-memberships',
			'woocommerce-memberships-for-teams',
			'woocommerce-memberships-mailchimp',
			'woocommerce-min-max-quantities',
			'woocommerce-multilingual',
			'woocommerce-one-page-checkout',
			'woocommerce-order-status-manager',
			'woocommerce-pdf-invoice',
			'woocommerce-pdf-watermark',
			'woocommerce-points-and-rewards',
			'woocommerce-pre-orders',
			'woocommerce-product-addons',
			'woocommerce-product-bundles',
			'woocommerce-product-feeds',
			'woocommerce-product-recommendations',
			'woocommerce-product-reviews-pro',
			'woocommerce-product-vendors',
			'woocommerce-sequential-order-numbers-pro',
			'woocommerce-shipping-local-pickup-plus',
			'woocommerce-shipping-per-product',
			'woocommerce-slack',
			'woocommerce-smart-coupons',
			'woocommerce-social-login',
			'woocommerce-subscription-downloads',
			'woocommerce-subscriptions',
			'woocommerce-tab-manager',
			'woocommerce-table-rate-shipping',
			'woocommerce-url-coupons',
			'woocommerce-warranty',
			'woocommerce-wholesale-pricing',
			'woocommerce-zapier',
			'woocommerce_additional_fees',
			'woocommerce_email_attachments',
			'wordpress-seo-extension',
			'wordpress-seo-premium',
			'wp-all-export-pro',
			'wp-all-import-pro',
			'wp-analytify-campaings',
			'wp-analytify-edd',
			'wp-analytify-email',
			'wp-analytify-goals',
			'wp-analytify-pro',
			'wp-analytify-woocommerce',
			'wp-booking-system',
			'wp-booking-system-authorize-net',
			'wp-booking-system-booking-manager',
			'wp-booking-system-booking-restrictions',
			'wp-booking-system-calendar-organiser',
			'wp-booking-system-contracts',
			'wp-booking-system-coupons-discounts',
			'wp-booking-system-customers',
			'wp-booking-system-email-reminders',
			'wp-booking-system-gopay',
			'wp-booking-system-inventory',
			'wp-booking-system-invoices',
			'wp-booking-system-mollie',
			'wp-booking-system-multiple-currencies',
			'wp-booking-system-paypal',
			'wp-booking-system-pricelabs',
			'wp-booking-system-redsys',
			'wp-booking-system-reporting',
			'wp-booking-system-search',
			'wp-booking-system-sms',
			'wp-booking-system-square',
			'wp-booking-system-stripe',
			'wp-booking-system-woocommerce',
			'wp-grid-builder',
			'wp-seo-multilingual',
			'wp-seopress',
			'wp-seopress-pro',
			'wp_all_export_jetengine_add_on',
			'wp_all_export_metabox_add_on',
			'wp_all_import_jetengine_add_on',
			'wp_all_import_metabox_add_on',
			'wpae-acf-add-on',
			'wpae-gravity-forms-export-addon',
			'wpae-user-add-on-pro',
			'wpae-woocommerce-add-on',
			'wpai-acf-add-on',
			'wpai-gravity-forms-import-addon',
			'wpai-linkcloak-add-on',
			'wpai-user-add-on',
			'wpai-woocommerce-add-on',
			'wpamelia',
			'wpgb-beaver-builder',
			'wpgb-bricks',
			'wpgb-caching',
			'wpgb-elementor',
			'wpgb-learndash',
			'wpgb-map-facet',
			'wpgb-meta-box',
			'wpgb-multilingual',
			'wpgb-oxygen',
			'wpgb-pods',
			'wpml-all-import',
			'wpml-cms-nav',
			'wpml-mailchimp-for-wp',
			'wpml-media-translation',
			'wpml-ninja-forms',
			'wpml-string-translation',
			'wpml-wpforms',
			'ws-form-woocommerce',
			'wswebinar',
			'yaymail',
			'yith-infinite-scrolling',
			'yith-woocommerce-ajax-navigation',
			'yoast-woo-seo',
			'zapier',
		],
		'themes' => [
			'astra',
			'Avada',
			'bricks',
			'Divi',
			'generatepress',
			'kadence',
			'oceanwp',
			'storefront',
			'woodmart',
		],
	];
}

/**
 * Returns the option key for a translation domain (used by settings and load_translation_file).
 *
 * @param string $domain Text domain (e.g. 'restrict-content-pro').
 * @return string Option key (e.g. 'translations-restrictcontentpro').
 */
function cps_hc_gems_translation_domain_to_option_key( $domain ) {
	return 'translations-' . str_replace( '-', '', $domain );
}

/**
 * Returns a human-readable display name for a translation domain (fallback when not in explicit map).
 *
 * @param string $domain Text domain (e.g. 'woocommerce-subscriptions').
 * @return string Humanized name (e.g. 'Woocommerce Subscriptions').
 */
function cps_hc_gems_translation_domain_to_display_name( $domain ) {
	return ucwords( str_replace( [ '-', '_' ], ' ', $domain ) );
}

/**
 * Returns the list of translation domain => human-readable name for plugins and themes.
 * Used in the modules settings page to show friendly names in the translation checkbox lists.
 *
 * @return array<string, string> Associative array of domain => display name.
 */
function cps_hc_gems_get_translation_domain_names() {
	$domains = cps_hc_gems_get_translation_domains();
	$all     = array_merge( $domains['plugins'], $domains['themes'] );

	// Explicit display names (extend over time for better display names).
	$explicit = [
		'acf' => 'Advanced Custom Fields',
		'acfml' => 'Advanced Custom Fields Multilingual',
		'addify-eobc' => 'Addify – B2B for WooCommerce',
		'addify-product-qty' => 'Addify – Advanced Product Quantity for WooCommerce',
		'addify_css' => 'Addify – Custom CSS',
		'addify_eobc' => 'Addify – B2B for WooCommerce',
		'addify_promo_bar' => 'Addify – Promotional Bar',
		'addify_reg' => 'Addify – Registration Fields',
		'addify_rfq' => 'Addify – Request a Quote for WooCommerce',
		'addify_videos' => 'Addify – Product Videos for WooCommerce',
		'admin-menu-editor-pro' => 'Admin Menu Editor Pro',
		'advanced-uptime-monitor-extension' => 'Advanced Uptime Monitor Extension (MainWP)',
		'affiliate-wp' => 'AffiliateWP',
		'affiliate-wp-lifetime-commissions' => 'AffiliateWP Lifetime Commissions',
		'affiliate-wp-recurring-referrals' => 'AffiliateWP Recurring Referrals',
		'affiliate-wp-tiered' => 'AffiliateWP Tiered Affiliate Rates',
		'affiliatewp-affiliate-area-shortcodes' => 'AffiliateWP Affiliate Area Shortcodes',
		'affiliatewp-affiliate-portal' => 'AffiliateWP Affiliate Portal',
		'affiliatewp-allowed-products' => 'AffiliateWP Allowed Products',
		'affiliatewp-custom-affiliate-slugs' => 'AffiliateWP Custom Affiliate Slugs',
		'affiliatewp-direct-link-tracking' => 'AffiliateWP Direct Link Tracking',
		'affiliatewp-multi-currency' => 'AffiliateWP Multi-Currency',
		'affiliatewp-multi-tier-commissions' => 'AffiliateWP Multi-Tier Commissions',
		'affiliatewp-rest-api-extended' => 'AffiliateWP REST API Extended',
		'affiliatewp-show-affiliate-coupons' => 'AffiliateWP Show Affiliate Coupons',
		'affiliatewp-signup-referrals' => 'AffiliateWP Signup Referrals',
		'affiliatewp-store-credit' => 'AffiliateWP Store Credit',
		'affiliatewp-woocommerce-redirect-affiliates' => 'AffiliateWP WooCommerce Redirect Affiliates',
		'affwp-affiliate-dashboard-sharing' => 'AffiliateWP Affiliate Dashboard Sharing',
		'affwp-paypal-payouts' => 'AffiliateWP PayPal Payouts',
		'all-in-one-wp-migration' => 'All-in-One WP Migration',
		'all-in-one-wp-migration-dropbox-extension' => 'All-in-One WP Migration Dropbox Extension',
		'all-in-one-wp-migration-ftp-extension' => 'All-in-One WP Migration FTP Extension',
		'all-in-one-wp-migration-gdrive-extension' => 'All-in-One WP Migration Google Drive Extension',
		'all-in-one-wp-migration-multisite-extension' => 'All-in-One WP Migration Multisite Extension',
		'all-in-one-wp-migration-onedrive-extension' => 'All-in-One WP Migration OneDrive Extension',
		'all-in-one-wp-migration-unlimited-extension' => 'All-in-One WP Migration Unlimited Extension',
		'all-in-one-wp-migration-url-extension' => 'All-in-One WP Migration URL Extension',
		'automatewoo' => 'AutomateWoo',
		'automatewoo-birthdays' => 'AutomateWoo Birthdays',
		'automatewoo-referrals' => 'AutomateWoo Referrals',
		'automatorwp' => 'AutomatorWP',
		'automatorwp-pro' => 'AutomatorWP Pro',
		'bloom' => 'Bloom',
		'boilerplate-extension' => 'Boilerplate Extension (MainWP)',
		'bought-together-for-woocommerce' => 'Bought Together for WooCommerce',
		'bricksextras' => 'Bricks Extras',
		'bricksforge' => 'Bricksforge',
		'buy-again-for-woocommerce' => 'Buy Again for WooCommerce',
		'cartflows' => 'CartFlows',
		'cartflows-pro' => 'CartFlows Pro',
		'checkout-wc' => 'CheckoutWC',
		'complianz-gdpr' => 'Complianz GDPR',
		'contact-form-7-multilingual' => 'Contact Form 7 Multilingual',
		'customize-my-account-page-for-woocommerce' => 'Customize My Account for WooCommerce',
		'database-cleaner' => 'Database Cleaner',
		'divi-menu-cart' => 'Divi Menu Cart',
		'divi-responsive-helper' => 'Divi Responsive Helper',
		'divi-toolbox' => 'Divi Toolbox',
		'divipasswords' => 'DiviPasswords',
		'dsm-supreme-modules-pro-for-divi' => 'Divi Supreme Modules Pro',
		'dynamic-content-for-elementor' => 'Dynamic Content for Elementor',
		'elementor' => 'Elementor',
		'elementor-pro' => 'Elementor Pro',
		'fluent-affiliate' => 'Fluent Affiliate',
		'fluent-affiliate-pro' => 'Fluent Affiliate Pro',
		'fluent-boards' => 'Fluent Boards',
		'fluent-boards-pro' => 'Fluent Boards Pro',
		'fluent-booking' => 'Fluent Booking',
		'fluent-booking-pro' => 'Fluent Booking Pro',
		'fluent-cart' => 'Fluent Cart',
		'fluent-cart-pro' => 'Fluent Cart Pro',
		'fluent-community' => 'Fluent Community',
		'fluent-community-pro' => 'Fluent Community Pro',
		'fluent-crm' => 'FluentCRM',
		'fluent-smtp' => 'FluentSMTP',
		'fluent-support' => 'Fluent Support',
		'fluent-support-pro' => 'Fluent Support Pro',
		'fluentcampaign-pro' => 'FluentCampaign Pro',
		'fluentform' => 'Fluent Forms',
		'fluentform-pdf' => 'Fluent Forms PDF',
		'fluentform-signature' => 'Fluent Forms Signature',
		'fluentformpro' => 'Fluent Forms Pro',
		'free-gifts-for-woocommerce' => 'Free Gifts for WooCommerce',
		'gappointments' => 'GAppointments',
		'generateblocks' => 'GenerateBlocks',
		'generateblocks-pro' => 'GenerateBlocks Pro',
		'gp-premium' => 'GP Premium (GeneratePress Premium)',
		'gravityforms-multilingual' => 'Gravity Forms Multilingual',
		'gravitysmtp' => 'Gravity SMTP',
		'imagify' => 'Imagify',
		'it-l10n-ithemes-security-pro' => 'iThemes Security Pro',
		'jet-appointments-booking' => 'JetAppointments',
		'jet-blocks' => 'JetBlocks',
		'jet-blog' => 'JetBlog',
		'jet-booking' => 'JetBooking',
		'jet-cw' => 'JetCompareWishlist',
		'jet-elements' => 'JetElements',
		'jet-engine' => 'JetEngine',
		'jet-engine-attachment-link-callback' => 'JetEngine Attachment Link Callback',
		'jet-engine-dynamic-charts-module' => 'JetEngine Dynamic Charts Module',
		'jet-engine-dynamic-tables-module' => 'JetEngine Dynamic Tables Module',
		'jet-engine-layout-switcher' => 'JetEngine Layout Switcher',
		'jet-engine-post-expiration-period' => 'JetEngine Post Expiration Period',
		'jet-engine-trim-callback' => 'JetEngine Trim Callback',
		'jet-form-builder' => 'JetFormBuilder',
		'jet-form-builder-address-autocomplete' => 'JetFormBuilder Address Autocomplete',
		'jet-form-builder-colorpicker' => 'JetFormBuilder Colorpicker',
		'jet-form-builder-convertkit-action' => 'JetFormBuilder ConvertKit Action',
		'jet-form-builder-formless-actions-endpoints' => 'JetFormBuilder Formless Actions Endpoints',
		'jet-form-builder-hr-select' => 'JetFormBuilder HR Select',
		'jet-form-builder-hubspot-action' => 'JetFormBuilder HubSpot Action',
		'jet-form-builder-limit-form-responses' => 'JetFormBuilder Limit Form Responses',
		'jet-form-builder-mailerlite-action' => 'JetFormBuilder MailerLite Action',
		'jet-form-builder-mailpoet-action' => 'JetFormBuilder MailPoet Action',
		'jet-form-builder-moosend-action' => 'JetFormBuilder Moosend Action',
		'jet-form-builder-paypal-subscriptions' => 'JetFormBuilder PayPal Subscriptions',
		'jet-form-builder-pdf' => 'JetFormBuilder PDF',
		'jet-form-builder-save-progress' => 'JetFormBuilder Save Progress',
		'jet-form-builder-schedule-forms' => 'JetFormBuilder Schedule Forms',
		'jet-form-builder-select-autocomplete' => 'JetFormBuilder Select Autocomplete',
		'jet-form-builder-stripe-gateway' => 'JetFormBuilder Stripe Gateway',
		'jet-form-builder-user-login-action' => 'JetFormBuilder User Login Action',
		'jet-form-builder-woo-action' => 'JetFormBuilder WooCommerce Action',
		'jet-menu' => 'JetMenu',
		'jet-popup' => 'JetPopup',
		'jet-reviews' => 'JetReviews',
		'jet-search' => 'JetSearch',
		'jet-smart-filters' => 'JetSmartFilters',
		'jet-styles-manager' => 'JetStyleManager',
		'jet-tabs' => 'JetTabs',
		'jet-theme-core' => 'JetThemeCore',
		'jet-tricks' => 'JetTricks',
		'jet-wc-product-table' => 'JetWooBuilder Product Table',
		'jet-woo-builder' => 'JetWooBuilder',
		'jet-woo-product-gallery' => 'JetWooBuilder Product Gallery',
		'js_composer' => 'WPBakery Page Builder',
		'ld-multilingual' => 'LearnDash Multilingual',
		'learndash' => 'LearnDash LMS',
		'learndash-2checkout' => 'LearnDash 2Checkout',
		'learndash-achievements' => 'LearnDash Achievements',
		'learndash-bbpress' => 'LearnDash bbPress',
		'learndash-certificate-builder' => 'LearnDash Certificate Builder',
		'learndash-course-grid' => 'LearnDash Course Grid',
		'learndash-course-reviews' => 'LearnDash Course Reviews',
		'learndash-edd' => 'LearnDash Easy Digital Downloads',
		'learndash-elementor' => 'LearnDash Elementor',
		'learndash-event-espresso' => 'LearnDash Event Espresso',
		'learndash-gravity-forms' => 'LearnDash Gravity Forms',
		'learndash-integrity' => 'LearnDash Integrity',
		'learndash-memberpress' => 'LearnDash MemberPress',
		'learndash-migration' => 'LearnDash Migration',
		'learndash-notifications' => 'LearnDash Notifications',
		'learndash-paidmemberships' => 'LearnDash Paid Memberships Pro',
		'learndash-restrict-content-pro' => 'LearnDash Restrict Content Pro',
		'learndash-samcart' => 'LearnDash SamCart',
		'learndash-tec' => 'LearnDash The Events Calendar',
		'learndash-thrivecart' => 'LearnDash ThriveCart',
		'learndash-woocommerce' => 'LearnDash WooCommerce',
		'learndash-zapier' => 'LearnDash Zapier',
		'mainwp' => 'MainWP Dashboard',
		'mainwp-api-backups-extension' => 'MainWP API Backups Extension',
		'mainwp-article-uploader-extension' => 'MainWP Article Uploader Extension',
		'mainwp-atarim-extension' => 'MainWP Atarim Extension',
		'mainwp-branding-extension' => 'MainWP Branding Extension',
		'mainwp-buddy-extension' => 'MainWP Buddy Extension',
		'mainwp-bulk-settings-manager' => 'MainWP Bulk Settings Manager',
		'mainwp-cache-control-extension' => 'MainWP Cache Control Extension',
		'mainwp-clean-and-lock-extension' => 'MainWP Clean and Lock Extension',
		'mainwp-clone-extension' => 'MainWP Clone Extension',
		'mainwp-code-snippets-extension' => 'MainWP Code Snippets Extension',
		'mainwp-comments-extension' => 'MainWP Comments Extension',
		'mainwp-custom-dashboard-extension' => 'MainWP Custom Dashboard Extension',
		'mainwp-custom-post-types' => 'MainWP Custom Post Types',
		'mainwp-database-updater-extension' => 'MainWP Database Updater Extension',
		'mainwp-domain-monitor-extension' => 'MainWP Domain Monitor Extension',
		'mainwp-favorites-extension' => 'MainWP Favorites Extension',
		'mainwp-file-uploader-extension' => 'MainWP File Uploader Extension',
		'mainwp-google-analytics-extension' => 'MainWP Google Analytics Extension',
		'mainwp-ithemes-security-extension' => 'MainWP iThemes Security Extension',
		'mainwp-jetpack-protect-extension' => 'MainWP Jetpack Protect Extension',
		'mainwp-jetpack-scan-extension' => 'MainWP Jetpack Scan Extension',
		'mainwp-lighthouse-extension' => 'MainWP Lighthouse Extension',
		'mainwp-maintenance-extension' => 'MainWP Maintenance Extension',
		'mainwp-piwik-extension' => 'MainWP Piwik Extension',
		'mainwp-post-dripper-extension' => 'MainWP Post Dripper Extension',
		'mainwp-post-plus-extension' => 'MainWP Post Plus Extension',
		'mainwp-pressable-extension' => 'MainWP Pressable Extension',
		'mainwp-pro-reports-extension' => 'MainWP Pro Reports Extension',
		'mainwp-rocket-extension' => 'MainWP WP Rocket Extension',
		'mainwp-ssl-monitor-extension' => 'MainWP SSL Monitor Extension',
		'mainwp-staging-extension' => 'MainWP Staging Extension',
		'mainwp-sucuri-extension' => 'MainWP Sucuri Extension',
		'mainwp-team-control' => 'MainWP Team Control',
		'mainwp-timecapsule-extension' => 'MainWP Time Capsule Extension',
		'mainwp-updraftplus-extension' => 'MainWP UpdraftPlus Extension',
		'mainwp-url-extractor-extension' => 'MainWP URL Extractor Extension',
		'mainwp-virusdie-extension' => 'MainWP Virusdie Extension',
		'mainwp-vulnerability-checker-extension' => 'MainWP Vulnerability Checker Extension',
		'mainwp-woocommerce-shortcuts-extension' => 'MainWP WooCommerce Shortcuts Extension',
		'mainwp-woocommerce-status-extension' => 'MainWP WooCommerce Status Extension',
		'mainwp-wordfence-extension' => 'MainWP Wordfence Extension',
		'mainwp-wp-compress-extension' => 'MainWP WP Compress Extension',
		'mb-admin-columns' => 'Meta Box Admin Columns',
		'mb-blocks' => 'Meta Box Blocks',
		'mb-custom-table' => 'Meta Box Custom Table',
		'mb-favorite-posts' => 'Meta Box Favorite Posts',
		'mb-frontend-submission' => 'Meta Box Frontend Submission',
		'mb-revision' => 'Meta Box Revision',
		'mb-settings-page' => 'Meta Box Settings Page',
		'mb-term-meta' => 'Meta Box Term Meta',
		'mb-testimonials' => 'Meta Box Testimonials',
		'mb-user-avatar' => 'Meta Box User Avatar',
		'mb-user-profile' => 'Meta Box User Profile',
		'meta-box' => 'Meta Box',
		'meta-box-builder' => 'Meta Box Builder',
		'meta-box-columns' => 'Meta Box Columns',
		'meta-box-conditional-logic' => 'Meta Box Conditional Logic',
		'meta-box-geolocation' => 'Meta Box Geolocation',
		'meta-box-group' => 'Meta Box Group',
		'meta-box-include-exclude' => 'Meta Box Include Exclude',
		'meta-box-show-hide' => 'Meta Box Show Hide',
		'meta-box-tabs' => 'Meta Box Tabs',
		'meta-box-template' => 'Meta Box Template',
		'meta-box-tooltip' => 'Meta Box Tooltip',
		'monarch' => 'Monarch',
		'ninja-forms-active-campaign' => 'Ninja Forms Active Campaign',
		'ninja-forms-conditionals' => 'Ninja Forms Conditional Logic',
		'ninja-forms-excel-export' => 'Ninja Forms Excel Export',
		'ninja-forms-layout-styles' => 'Ninja Forms Layout & Styles',
		'ninja-forms-multi-part' => 'Ninja Forms Multi-Part Forms',
		'ninja-forms-save-progress' => 'Ninja Forms Save Progress',
		'ninja-forms-stripe' => 'Ninja Forms Stripe',
		'ninja-forms-uploads' => 'Ninja Forms File Uploads',
		'ninja-forms-user-management' => 'Ninja Forms User Management',
		'ninja-forms-webhooks' => 'Ninja Forms Webhooks',
		'oxyextras' => 'OxyExtras',
		'oxygen' => 'Oxygen Builder',
		'oxygen-gutenberg' => 'Oxygen Gutenberg',
		'oxygen-woocommerce' => 'Oxygen WooCommerce',
		'perfmatters' => 'Perfmatters',
		'pewc' => 'Product Options for WooCommerce',
		'plgfyplv' => 'Plugify Player',
		'polylang-pro' => 'Polylang Pro',
		'polylang-wc' => 'Polylang for WooCommerce',
		'qala-product-price-history' => 'Product Price History for WooCommerce',
		'quadmenu' => 'QuadMenu',
		'quadmenu-pro' => 'QuadMenu Pro',
		'rcp' => 'Restrict Content Pro',
		'revslider' => 'Slider Revolution',
		'rocket' => 'WP Rocket',
		'sfwd-lms' => 'LearnDash LMS',
		'sitepress-multilingual-cms' => 'WPML Multilingual CMS',
		'termageddon-for-mainwp' => 'Termageddon for MainWP',
		'translatepress-multilingual' => 'TranslatePress Multilingual',
		'tutor-pro' => 'Tutor LMS Pro',
		'uael' => 'Ultimate Addons for Elementor',
		'updraftplus' => 'UpdraftPlus',
		'userpro' => 'UserPro',
		'wc_gf_addons' => 'WooCommerce Gravity Forms Product Add-ons',
		'wc_name_your_price' => 'WooCommerce Name Your Price',
		'wc_wishlist' => 'WooCommerce Wishlists',
		'woo-af-drpc' => 'WooCommerce Deposits',
		'woo-price-per-unit-pro' => 'Price Per Unit Pro for WooCommerce',
		'woocommerce-account-funds' => 'WooCommerce Account Funds',
		'woocommerce-additional-variation-images' => 'WooCommerce Additional Variation Images',
		'woocommerce-advanced-notifications' => 'WooCommerce Advanced Notifications',
		'woocommerce-all-products-for-subscriptions' => 'WooCommerce All Products for Subscriptions',
		'woocommerce-api-manager' => 'WooCommerce API Manager',
		'woocommerce-appointments' => 'WooCommerce Appointments',
		'woocommerce-back-in-stock-notifications' => 'WooCommerce Back In Stock Notifications',
		'woocommerce-bookings' => 'WooCommerce Bookings',
		'woocommerce-bulk-stock-management' => 'WooCommerce Bulk Stock Management',
		'woocommerce-checkout-add-ons' => 'WooCommerce Checkout Add-Ons',
		'woocommerce-checkout-field-editor' => 'WooCommerce Checkout Field Editor',
		'woocommerce-composite-products' => 'WooCommerce Composite Products',
		'woocommerce-conditional-shipping-and-payments' => 'WooCommerce Conditional Shipping and Payments',
		'woocommerce-cost-of-goods' => 'WooCommerce Cost of Goods',
		'woocommerce-deposits' => 'WooCommerce Deposits',
		'woocommerce-dynamic-pricing' => 'WooCommerce Dynamic Pricing',
		'woocommerce-email-customizer' => 'WooCommerce Email Customizer',
		'woocommerce-eu-vat-number' => 'WooCommerce EU VAT Number',
		'woocommerce-google-adwords-conversion-tracking-tag' => 'WooCommerce Google Ads Conversion Tracking',
		'woocommerce-google-analytics-pro' => 'WooCommerce Google Analytics Pro',
		'woocommerce-mailchimp-integration' => 'WooCommerce MailChimp',
		'woocommerce-measurement-price-calculator' => 'WooCommerce Measurement Price Calculator',
		'woocommerce-memberships' => 'WooCommerce Memberships',
		'woocommerce-memberships-for-teams' => 'WooCommerce Memberships for Teams',
		'woocommerce-memberships-mailchimp' => 'WooCommerce Memberships MailChimp',
		'woocommerce-min-max-quantities' => 'WooCommerce Min/Max Quantities',
		'woocommerce-multilingual' => 'WooCommerce Multilingual',
		'woocommerce-one-page-checkout' => 'WooCommerce One Page Checkout',
		'woocommerce-order-status-manager' => 'WooCommerce Order Status Manager',
		'woocommerce-pdf-invoice' => 'WooCommerce PDF Invoice',
		'woocommerce-pdf-watermark' => 'WooCommerce PDF Watermark',
		'woocommerce-points-and-rewards' => 'WooCommerce Points and Rewards',
		'woocommerce-pre-orders' => 'WooCommerce Pre-Orders',
		'woocommerce-product-addons' => 'WooCommerce Product Add-Ons',
		'woocommerce-product-bundles' => 'WooCommerce Product Bundles',
		'woocommerce-product-feeds' => 'WooCommerce Product Feeds',
		'woocommerce-product-recommendations' => 'WooCommerce Product Recommendations',
		'woocommerce-product-reviews-pro' => 'WooCommerce Product Reviews Pro',
		'woocommerce-product-vendors' => 'WooCommerce Product Vendors',
		'woocommerce-sequential-order-numbers-pro' => 'WooCommerce Sequential Order Numbers Pro',
		'woocommerce-shipping-local-pickup-plus' => 'WooCommerce Local Pickup Plus',
		'woocommerce-shipping-per-product' => 'WooCommerce Per Product Shipping',
		'woocommerce-slack' => 'WooCommerce Slack',
		'woocommerce-smart-coupons' => 'WooCommerce Smart Coupons',
		'woocommerce-social-login' => 'WooCommerce Social Login',
		'woocommerce-subscription-downloads' => 'WooCommerce Subscription Downloads',
		'woocommerce-subscriptions' => 'WooCommerce Subscriptions',
		'woocommerce-tab-manager' => 'WooCommerce Tab Manager',
		'woocommerce-table-rate-shipping' => 'WooCommerce Table Rate Shipping',
		'woocommerce-url-coupons' => 'WooCommerce URL Coupons',
		'woocommerce-warranty' => 'WooCommerce Warranty',
		'woocommerce-wholesale-pricing' => 'WooCommerce Wholesale Pricing',
		'woocommerce-zapier' => 'WooCommerce Zapier',
		'woocommerce_additional_fees' => 'WooCommerce Additional Fees',
		'woocommerce_email_attachments' => 'WooCommerce Email Attachments',
		'wordpress-seo-extension' => 'Yoast SEO Extensions',
		'wordpress-seo-premium' => 'Yoast SEO Premium',
		'wp-all-export-pro' => 'WP All Export Pro',
		'wp-all-import-pro' => 'WP All Import Pro',
		'wp-analytify-campaings' => 'Analytify Campaigns',
		'wp-analytify-edd' => 'Analytify for EDD',
		'wp-analytify-email' => 'Analytify Email Notifications',
		'wp-analytify-goals' => 'Analytify Goals',
		'wp-analytify-pro' => 'Analytify Pro',
		'wp-analytify-woocommerce' => 'Analytify for WooCommerce',
		'wp-booking-system' => 'WP Booking System',
		'wp-booking-system-authorize-net' => 'WP Booking System Authorize.Net',
		'wp-booking-system-booking-manager' => 'WP Booking System Booking Manager',
		'wp-booking-system-booking-restrictions' => 'WP Booking System Booking Restrictions',
		'wp-booking-system-calendar-organiser' => 'WP Booking System Calendar Organiser',
		'wp-booking-system-contracts' => 'WP Booking System Contracts',
		'wp-booking-system-coupons-discounts' => 'WP Booking System Coupons & Discounts',
		'wp-booking-system-customers' => 'WP Booking System Customers',
		'wp-booking-system-email-reminders' => 'WP Booking System Email Reminders',
		'wp-booking-system-gopay' => 'WP Booking System GoPay',
		'wp-booking-system-inventory' => 'WP Booking System Inventory',
		'wp-booking-system-invoices' => 'WP Booking System Invoices',
		'wp-booking-system-mollie' => 'WP Booking System Mollie',
		'wp-booking-system-multiple-currencies' => 'WP Booking System Multiple Currencies',
		'wp-booking-system-paypal' => 'WP Booking System PayPal',
		'wp-booking-system-pricelabs' => 'WP Booking System PriceLabs',
		'wp-booking-system-redsys' => 'WP Booking System Redsys',
		'wp-booking-system-reporting' => 'WP Booking System Reporting',
		'wp-booking-system-search' => 'WP Booking System Search',
		'wp-booking-system-sms' => 'WP Booking System SMS',
		'wp-booking-system-square' => 'WP Booking System Square',
		'wp-booking-system-stripe' => 'WP Booking System Stripe',
		'wp-booking-system-woocommerce' => 'WP Booking System WooCommerce',
		'wp-grid-builder' => 'WP Grid Builder',
		'wp-seo-multilingual' => 'Yoast SEO Multilingual',
		'wp-seopress' => 'SEOPress',
		'wp-seopress-pro' => 'SEOPress Pro',
		'wp_all_export_jetengine_add_on' => 'WP All Export JetEngine Add-On',
		'wp_all_export_metabox_add_on' => 'WP All Export Meta Box Add-On',
		'wp_all_import_jetengine_add_on' => 'WP All Import JetEngine Add-On',
		'wp_all_import_metabox_add_on' => 'WP All Import Meta Box Add-On',
		'wpae-acf-add-on' => 'WP All Export ACF Add-On',
		'wpae-gravity-forms-export-addon' => 'WP All Export Gravity Forms Add-On',
		'wpae-user-add-on-pro' => 'WP All Export User Add-On Pro',
		'wpae-woocommerce-add-on' => 'WP All Export WooCommerce Add-On',
		'wpai-acf-add-on' => 'WP All Import ACF Add-On',
		'wpai-gravity-forms-import-addon' => 'WP All Import Gravity Forms Add-On',
		'wpai-linkcloak-add-on' => 'WP All Import LinkCloak Add-On',
		'wpai-user-add-on' => 'WP All Import User Add-On',
		'wpai-woocommerce-add-on' => 'WP All Import WooCommerce Add-On',
		'wpamelia' => 'WP Amelia',
		'wpgb-beaver-builder' => 'WP Grid Builder Beaver Builder',
		'wpgb-bricks' => 'WP Grid Builder Bricks',
		'wpgb-caching' => 'WP Grid Builder Caching',
		'wpgb-elementor' => 'WP Grid Builder Elementor',
		'wpgb-learndash' => 'WP Grid Builder LearnDash',
		'wpgb-map-facet' => 'WP Grid Builder Map Facet',
		'wpgb-meta-box' => 'WP Grid Builder Meta Box',
		'wpgb-multilingual' => 'WP Grid Builder Multilingual',
		'wpgb-oxygen' => 'WP Grid Builder Oxygen',
		'wpgb-pods' => 'WP Grid Builder Pods',
		'wpml-all-import' => 'WPML All Import',
		'wpml-cms-nav' => 'WPML CMS Navigation',
		'wpml-mailchimp-for-wp' => 'WPML MailChimp for WordPress',
		'wpml-media-translation' => 'WPML Media Translation',
		'wpml-ninja-forms' => 'WPML Ninja Forms',
		'wpml-string-translation' => 'WPML String Translation',
		'wpml-wpforms' => 'WPML WPForms',
		'ws-form-woocommerce' => 'WS Form WooCommerce',
		'wswebinar' => 'WebinarPress',
		'yaymail' => 'YayMail',
		'yith-infinite-scrolling' => 'YITH Infinite Scrolling',
		'yith-woocommerce-ajax-navigation' => 'YITH WooCommerce Ajax Product Filter',
		'yoast-woo-seo' => 'Yoast WooCommerce SEO',
		'zapier' => 'Zapier',
		// Themes
		'astra' => 'Astra',
		'Avada' => 'Avada',
		'bricks' => 'Bricks',
		'Divi' => 'Divi',
		'generatepress' => 'GeneratePress',
		'kadence' => 'Kadence',
		'oceanwp' => 'OceanWP',
		'storefront' => 'Storefront',
		'woodmart' => 'WoodMart',
	];

	$names = [];
	foreach ( $all as $domain ) {
		$names[ $domain ] = $explicit[ $domain ] ?? cps_hc_gems_translation_domain_to_display_name( $domain );
	}

	return $names;
}
